-- Ejecutar una sola vez en Supabase > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  name text not null default 'Lukiplay',
  slogan text not null default 'Juguetes que inspiran grandes aventuras',
  welcome text not null default 'La sonrisa de la familia empieza aquí',
  phone text not null default '56933371875',
  whatsapp_message text not null default 'Hola, me interesa {producto} de ${precio}. ¿Está disponible?',
  logo_url text not null default '',
  background_url text not null default '',
  primary_color text not null default '#102858',
  secondary_color text not null default '#18a8aa',
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price integer not null check (price >= 0),
  old_price integer check (old_price is null or old_price >= 0),
  category text not null default 'Otros',
  description text not null default '',
  image_url text not null default '',
  availability text not null default 'Disponible' check (availability in ('Disponible','Pocas unidades','Agotado')),
  featured boolean not null default false,
  hidden boolean not null default false,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('view','product','whatsapp','share')),
  product_id uuid references public.products(id) on delete set null,
  product_name text,
  created_at timestamptz not null default now()
);

insert into public.store_settings (id) values (1) on conflict (id) do nothing;

alter table public.store_settings enable row level security;
alter table public.products enable row level security;
alter table public.analytics_events enable row level security;

create or replace function public.is_catalog_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(auth.jwt() ->> 'email','') = 'nilsabethn@gmail.com' $$;

drop policy if exists "public read settings" on public.store_settings;
create policy "public read settings" on public.store_settings for select using (true);
drop policy if exists "admin update settings" on public.store_settings;
create policy "admin update settings" on public.store_settings for update using (public.is_catalog_admin()) with check (public.is_catalog_admin());

drop policy if exists "public read visible products" on public.products;
create policy "public read visible products" on public.products for select using (hidden = false or public.is_catalog_admin());
drop policy if exists "admin insert products" on public.products;
create policy "admin insert products" on public.products for insert with check (public.is_catalog_admin());
drop policy if exists "admin update products" on public.products;
create policy "admin update products" on public.products for update using (public.is_catalog_admin()) with check (public.is_catalog_admin());
drop policy if exists "admin delete products" on public.products;
create policy "admin delete products" on public.products for delete using (public.is_catalog_admin());

drop policy if exists "public insert analytics" on public.analytics_events;
create policy "public insert analytics" on public.analytics_events for insert with check (true);
drop policy if exists "admin read analytics" on public.analytics_events;
create policy "admin read analytics" on public.analytics_events for select using (public.is_catalog_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('catalog-media','catalog-media',true,8388608,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true;

drop policy if exists "public read catalog images" on storage.objects;
create policy "public read catalog images" on storage.objects for select using (bucket_id = 'catalog-media');
drop policy if exists "admin upload catalog images" on storage.objects;
create policy "admin upload catalog images" on storage.objects for insert with check (bucket_id = 'catalog-media' and public.is_catalog_admin());
drop policy if exists "admin update catalog images" on storage.objects;
create policy "admin update catalog images" on storage.objects for update using (bucket_id = 'catalog-media' and public.is_catalog_admin());
drop policy if exists "admin delete catalog images" on storage.objects;
create policy "admin delete catalog images" on storage.objects for delete using (bucket_id = 'catalog-media' and public.is_catalog_admin());

create index if not exists products_position_idx on public.products(position);
create index if not exists products_category_idx on public.products(category);
create index if not exists analytics_type_idx on public.analytics_events(event_type);
create index if not exists analytics_created_idx on public.analytics_events(created_at);
